package com.svsa.ct.model.enums;

public enum OrigemDenuncia {
    OFICIO_RECEBIDO,
    ENTREGA_DE_DOCUMENTOS,
    REUNIOES_COM_REDE,
    CAPACITACAO,
    DENUNCIA,
    DENUNCIA_POR_TELEFONE,
    DISQUE_100,
    PLANTAO_APOS_17H,
    PROMOTORIA,
    JUIZ,
    CONSELHO_TUTELAR,
    CRAS,
    CREAS,
    CMDCA,
    HOSPITAL,
    SAUDE,
    DELEGACIA,
    GCM,
    PM,
    ESCOLA,
    DELEGACIA_DE_ENSINO,
    ENTIDADES;
}
